#!/usr/bin/env python
#
# Calculate the prime below a number
import sys

max_num = 1

if len(sys.argv) > 1:
    max_num = int(sys.argv[1])

nums = range(2,max_num+1) 

i = 0
while i < len(nums):
    length = len(nums)
    nums = [nums[i]] + [n for n in nums if not n % nums[i] == 0]
    if len(nums) == length:
        break
    i += 1

print " ".join([str(n) for n in sorted(nums)])
