#!/bin/sh

remotedir="tobias:/var/torrents/watch"

remotepath=${remotedir}/$(echo $(basename "$1") | tr -d " ()[]" | head -c16):$(echo $(date) | md5sum | tr " =-" "\b" | head -c8).torrent
echo Sending $(basename "$1")
echo to ${remotepath}
scp "$1" ${remotepath} && rm "$1"
